apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rtppgjj9e-nodejs 
  janus-idp.io/tekton: rtppgjj9e-nodejs
  backstage.io/kubernetes-id: rtppgjj9e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rtppgjj9e-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml